In [1]:
# importing libraries

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats
#import researchpy as rp

In [3]:
# importing csv file to python

In [4]:
data = pd.read_csv('Sales_add.csv')

In [5]:
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [7]:
# on checking, data is having 5 columns and no null data in any columns

# The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.

In [8]:
# Formulating Hypothesis
# H0: There is no increase in sales after stepping to digital marketing,μ1=μ2
# H1: There is increase in sales after stepping to digital marketing,μ1>μ2

In [9]:
# Since we want to test the increase in sales for same sample, 
# we will use paired sample t test

In [10]:
before_add = data['Sales_before_digital_add(in $)']
after_add = data['Sales_After_digital_add(in $)']

In [11]:
# Finding Test criteria and Pvalue

In [12]:
tvalue,pvalue = stats.ttest_rel(before_add,after_add,alternative='less')

In [13]:
stats.ttest_rel(before_add,after_add,alternative='less')

Ttest_relResult(statistic=-12.09070525287017, pvalue=3.168333502287889e-11)

In [14]:
if (pvalue <0.05):
    print('Reject H0:There is no increase in sales after stepping to digital marketing')
else:
    print('Reject H1:There is increase in sales after stepping to digital marketing')

Reject H0:There is no increase in sales after stepping to digital marketing


As per the hypothesis testing there is **indication of increase in sales** after **stepping into digital marketing**

# The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [15]:
data1=data.groupby('Region')['Manager'].value_counts().unstack()

In [16]:
# grouping variables and factors into row and columns to do chi square test to check dependency
# Hypothesis
# H0:Region and Manager features are independent
# H1:Region and Manager features are dependent

In [17]:
data1

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [18]:
# Cross Checking contingency table using crosstab function

In [19]:
pd.crosstab(data['Region'],data['Manager'])

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [20]:
#perform the Chi-Square Test of Independence since we have contingency table of frequencies
chivalue,pvalue,df,expvalues=stats.chi2_contingency(data1)

In [21]:
print('Chi sqaure Test Statistic:',chivalue)
print('Pvalue of test data;',pvalue)
print('Degrees of Freedom:',df)
print('expected observations of data:\n',expvalues)

Chi sqaure Test Statistic: 3.050566893424036
Pvalue of test data; 0.5493991051158094
Degrees of Freedom: 4
expected observations of data:
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [22]:
# chi square criteria value for significance of 0.05 and degrees of freedom (3-1)*(3-1) =4 
chicriteria=stats.chi2.ppf(1-0.05,4)
stats.chi2.ppf(1-0.05,df=4)

9.487729036781154

In [23]:
if(chivalue>chicriteria and pvalue<0.05):
    print('Reject H0: Region and Manager features are independent')
else:
    print('Reject H1:Region and Manager features are dependent')

Reject H1:Region and Manager features are dependent


As per Chi square test for independence the Features **Region** and **Manager** are **independent**